pages:
  image: registry.gitlab.com/wave-engineering/spreadsheet/builder:latest
  script:
  - pip install -r python/requirements-dev-frozen.txt
  - npm install -g jsdoc@3.5
  - make html
  - git bundle create build/html/_static/repo.bundle --branches HEAD
  - mv build/html public

  artifacts:
    paths:
    - public

python:
  image: python:3.7
  script:
  - cd python
  - pip install -r requirements-dev.txt
  - pytest sheet/ tests/
  - black --check sheet tests

javascript:
  image: node:10.15.0
  script:
  - cd javascript
  - npm i --dev
  - npm test
  - node_modules/prettier/bin-prettier.js --list-different sheet/*.js test/*.js
