python:
  image: python:3.7
  script:
  - cd python
  - pip install -r requirements-dev.txt
  - pytest sheet/ tests/
  - black --check sheet tests

javascript:
  image: node:10.15.0
  script:
  - cd javascript
  - npm i --dev
  - npm test
